services:
  postgres:
    image: pgvector/pgvector:pg18-bookworm
    container_name: gran_publicador_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gran
      POSTGRES_PASSWORD: gran_password
      POSTGRES_DB: gran_db
    ports:
      - '5432:5432'
    volumes:
      - gran_p_postgres_data:/var/lib/postgresql/data
    user: '1000:1000'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U gran -d gran_db']
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8-alpine
    container_name: gran_publicador_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    #volumes:
    #  - ./test-data/redis:/data
    user: '1000:1000'
    command: redis-server --save "" --appendonly no

volumes:
  gran_p_postgres_data:
