services:
  microservice:
    image: ghcr.io/bozonx/gran-publicador:latest
    container_name: gran-publicador
    hostname: gran-publicador
    restart: unless-stopped
    stop_grace_period: 30s
    expose:
      - 8080
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - TZ=UTC
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=8080
      - LOG_LEVEL=warn
      - DATABASE_URL=postgresql://gran:gran_password@postgres:5432/gran_db?schema=public
      - JWT_SECRET=slkdf923598ksfdo7853kjlksdfu4oi5jkssf908kj
      - TELEGRAM_BOT_TOKEN=your_token_here
      - API_KEY=your_api_key_here
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - postgres
    healthcheck:
      test: [ 'CMD-SHELL', 'wget -qO- http://127.0.0.1:8080/api/v1/health || exit 1' ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - gran_p_redis_data:/data

  postgres:
    image: pgvector/pgvector:pg18-bookworm
    container_name: gran-publicador-postgres
    hostname: gran-publicador-postgres
    restart: unless-stopped
    expose:
      - 5432
    #ports:
    #  - '5432:5432'
    volumes:
      - gran_p_postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: gran
      POSTGRES_PASSWORD: gran_password
      POSTGRES_DB: gran_db
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U gran -d gran_db || exit 1' ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  gran_p_redis_data:
  gran_p_postgres_data:
